### ISSUE TITLE
Error in training the model

### ISSUE THREAD

**Issue by nimishdesai1989** [armaanpriyadarshan/Training-a-Custom-TensorFlow-2.X-Object-Detector#19]
@armaanpriyadarshan : I get the below error when trying to train the model. I have confirmed that the file is present in the folder. Can you please help.

self._read_buf = _pywrap_file_io.BufferedInputStream(
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: models\my_ssd_mobilenet_v2_fpnlite\pipeline.config : The system cannot find the path specified.
; No such process

**Comment by ekesdf** [comment]
the pipeline.config file is not in the right place 
so just follow the tutorial and copy the pipeline.config file into the **models\my_ssd_mobilenet_v2_fpnlite** folder

**Comment by Drzarina78** [comment]
Hi Armaan, When i compile this i got KeyError. I used the same dataset as yours.

(tensorflow) C:\Users\ACER\Desktop\Tensorflow\scripts\preprocessing>python generate_tfrecord.py -x C:\Users\ACER\Desktop\Tensorflow\workspace\training_demo\images\train -l C:\Users\ACER\Desktop\Tensorflow\workspace\training_demo\annotations\label_map.pbtxt -o C:\Users\ACER\Desktop\Tensorflow\workspace\training_demo\annotations\train.record
Traceback (most recent call last):
  File "generate_tfrecord.py", line 168, in <module>
    tf.app.run()
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 158, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 132, in create_tf_example
    classes.append(class_text_to_int(row['class']))
  File "generate_tfrecord.py", line 101, in class_text_to_int
    return label_map_dict[row_label]
KeyError: 'Acetaminophen 325 MG Oral Tablet'

Thanks in advance

**Comment by Drzarina78** [comment]
> Hi Armaan, When i compile this i got KeyError. I used the same dataset as yours.
> 
> (tensorflow) C:\Users\ACER\Desktop\Tensorflow\scripts\preprocessing>python generate_tfrecord.py -x C:\Users\ACER\Desktop\Tensorflow\workspace\training_demo\images\train -l C:\Users\ACER\Desktop\Tensorflow\workspace\training_demo\annotations\label_map.pbtxt -o C:\Users\ACER\Desktop\Tensorflow\workspace\training_demo\annotations\train.record
> Traceback (most recent call last):
> File "generate_tfrecord.py", line 168, in
> tf.app.run()
> File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
> _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
> File "D:\Anaconda\envs\tensorflow\lib\site-packages\absl\app.py", line 303, in run
> _run_main(main, args)
> File "D:\Anaconda\envs\tensorflow\lib\site-packages\absl\app.py", line 251, in _run_main
> sys.exit(main(argv))
> File "generate_tfrecord.py", line 158, in main
> tf_example = create_tf_example(group, path)
> File "generate_tfrecord.py", line 132, in create_tf_example
> classes.append(class_text_to_int(row['class']))
> File "generate_tfrecord.py", line 101, in class_text_to_int
> return label_map_dict[row_label]
> KeyError: 'Acetaminophen 325 MG Oral Tablet'
> 
> Thanks in advance

Thanks Allah. I suddenly got the solution of mine. Just to open the .xml file and see what exactly the id that u name. should be same as what inside label_map.pbtxt
